### ISSUE TITLE
Thermal Throttling at 65 deg C

### ISSUE THREAD

**Issue by Jinglong-Hongjun** [yusifsalam/t490-macos#11]
Here is the result after disabling CPU Friend & CPU Friend Data Provider Kexts.
Clock speed is 1.5GHz average (and the score should be around 58x-61x)
![Screen Shot 2563-09-18 at 22 59 50](https://user-images.githubusercontent.com/71412080/93619460-c201d500-fa02-11ea-88d5-089d08ca0aa8.png)

I can do 1500-1600 Cinebench R20 on Windows 10.

**Comment by yusifsalam** [comment]
Can you update to the latest bios? Lackluster performance was a known issue on earlier lenovo bios versions for thinkpads.

**Comment by Jinglong-Hongjun** [comment]
> Can you update to the latest bios? Lackluster performance was a known issue on earlier lenovo bios versions for thinkpads.

Thank you, I will try that.
Actually, this current bios version (1.49) is working well on Windows 10 (with ThrottleStop) but the newer one is just bad :( (especially with discrete graphics model)

**Comment by Jinglong-Hongjun** [comment]
Thank you so much
The problems are solved!
CPU is working under 18w power limit which is better than 65deg C temperature limit (9-11w) and battery indicator is working now.
![Screen Shot 2563-09-19 at 00 36 16](https://user-images.githubusercontent.com/71412080/93628165-50308800-fa10-11ea-9ef3-34627e604799.png)

**Comment by yusifsalam** [comment]
Haha, that's great to hear!
I think you should still play around with power profiles using CPUFriend, because I'm getting a better score on my i5 processor, and yours is a higher clocked i7. 
Since the throttling issue is resolved, I'm closing the issue but feel free to report on your results here if you end up tweaking stuff.

**Comment by Jinglong-Hongjun** [comment]
New result :) I got better score on Windows 10 (due to undervolting & disabling meltdown/spectre patches) but still so much better. Thank you
![Screen Shot 2563-09-19 at 22 27 06](https://user-images.githubusercontent.com/71412080/93670680-62213200-fac7-11ea-9ab9-14ed1f87178a.png)
