### ISSUE TITLE
Tested Big Sur Beta?

### ISSUE THREAD

**Issue by way2ezee** [yusifsalam/t490-macos#21]
Hi,

Is there any luck trying this guide with Big Sur beta? 

Thanks

**Comment by denzilferreira** [comment]
Too early. Wait for the final release as OpenCore itself is also work in progress...

**Comment by yusifsalam** [comment]
I haven't tested it personally, waiting for the official release. However, everything should just work without needing to do any modifications (you might have to update the kexts but that's about it). If you end up testing Big Sur yourself, let us know how it goes.

**Comment by way2ezee** [comment]
![IMG20201002193304](https://user-images.githubusercontent.com/16752960/94934548-862e3b80-04e9-11eb-9a35-19f2719ec19b.jpg)

**Comment by yusifsalam** [comment]
try with airportitlwm disabled or install the big sur kext version from
the itlwm repo

**Comment by yusifsalam** [comment]
oh right. you edited the screenshot, now it looks like an SSD issue. do you have access to another SSD that you could try with?

**Comment by way2ezee** [comment]
Nope, unfortunately

**Comment by yusifsalam** [comment]
have you tried disabling all ACPI paches and only keeping the essential kexts enabled? The only kexts you need are VirtualSMC and Lilu, also VoodooPS2 if you also want to use the keyboard, VoodooRMI and VoodooSMBus for the trackpad.

**Comment by way2ezee** [comment]
I may have to change sector size to 4096 from 512. I have checked it is
512. Another issue I have to solve is can I restore clonezilla image of
encrypted windows partition after making sectoral changes?

I am new to opencore. Is it possible to select and choose plist just like
with clover pressing 'o' after clover.efi is loaded, How?

**Comment by yusifsalam** [comment]
> Another issue I have to solve is can I restore clonezilla image/snapshot of
encrypted windows partition after making sectoral changes

I don't have experience with clonezilla, so can't answer this. 

> Is it possible to select and choose plist just like
with clover pressing 'o' after clover bootloader is loaded, How?

I don't think OC has this feature unfortunately.

**Comment by yusifsalam** [comment]
You might be onto something with the sector size. I just checked mine and it's 4096 bytes.

**Comment by way2ezee** [comment]
Where can I place "Kernel and Kext patches" using OC. I want to test this patch/
```
Name*:  IONVMeFamily
Find*  [ HEX ] :  f6c1100f 85410 100 00
Replace*  [ HEX ] :  f6c1010f 85410 100 00
Comment: IONVMeFamily Preferred Block Size 0x10 -> 0x01 (c) Pike R. Alpha implemented by syscl adapted for 10.13.x-10.14 by Ricky
MatchOS:  10.13&10.14
```

**Comment by Jinglong-Hongjun** [comment]
I also had a problem with SK Hynix SSD. It just froze at the apple logo (with process bar that around 50%)
I didn't know what to do with this ssd so I swapped out with WD blue SSD and it works fine :)

**Comment by denzilferreira** [comment]
FYI: There are SSD firmware updates that may solve this. I just updated my WDC PC SN730 SDBQNTY-512G-1001  SSD and notice a noticeable difference in performance. In bench, I am now getting performance in read and write speeds (previously: W: 2100, R: 2000) and now at Write: 2500 MB/s, Read: 2400 MB/s - tested with Blackmagicdesign Disk Speed Test (free on [App Store](https://apps.apple.com/fi/app/blackmagic-disk-speed-test/id425264550?mt=12))

To update, I live booted Fedora 32 and ran:
> sudo fwupmgr get-updates

This will give you a list of devices that have updates (perks of having a Lenovo :D)

To update, you will need to do it device by device. You can queue multiple updates (only reboot once you have gone through all of them).
> sudo fwupmgr update DEVICE_ID

Reboot after this and the BIOS will find and apply the updates before booting into macOS.

**Comment by yusifsalam** [comment]
Closing for now since no response from author in a week

**Comment by way2ezee** [comment]
I have opened a ticket with Lenovo care. I will update on it.

**Comment by yusifsalam** [comment]
Probably under ACPI-Patches. Take a look at the OC documentation.
https://github.com/acidanthera/OpenCorePkg/blob/cad9e24d8698b323fba1498ac9efacfcb27c378f/Docs/Configuration.pdf
