### ISSUE TITLE
Power configuration

### ISSUE THREAD

**Issue by niktrane** [yusifsalam/t490-macos#24]
Hi. Install worked perfectly. Thanks so much. Only thing for me is battery life is terrible. I saw something about a script but have no idea how to get it working. Could someone please help me. Thanks for the great hackintosh guide.

**Comment by yusifsalam** [comment]
Can you elaborate which script you mean? 

Also, what is "terrible" battery life? For example I'm getting about 5-6h, which is obviously not as good as linux or windows but it's not really that much worse - this laptop simply does not have great battery life regardless of the OS. Also keep in mind that when you first install macOS, it will be indexing files in the background, which drains battery, when the indexing is complete, you should see improved results.

**Comment by niktrane** [comment]
Hi. Thanks for getting back to me. I’m talking about the CPU friend friend script. Forgive my ignorance. Completely new to hackintosh. I get about 3 hours at the moment. Even when doing nothing battery runs down quickly. 

Nick Williams

**Comment by yusifsalam** [comment]
Ok, 3h is pretty bad. What is your CPU/GPU? How about BIOS and EC version?
You can download Intel Power Gadget and check how much power your CPU is using on idle/under load. Also from activity  monitor check which processes are using most CPU resources. Usually you can search for "x process using CPU too much" and get a bunch of hits. For example if you have a massive Photos library, macOS will try to analyze the contents of your photos and videos, so you'll have a process called "bird" hogging the CPU if I recall correctly.

For CPUFriendFriend, you just start the script, input the base frequency (this depends on the exact CPU model you have, you should check your base frequency [here](https://ark.intel.com/content/www/us/en/ark.html)), and then the energy performance mode as hex value. The script will create a kext file called CPUFriendFriendDataProvider.kext, which you will then need to put inside OC/Kexts overwriting the one that's already there.

**Comment by yusifsalam** [comment]
Closing (no response from author)
