### ISSUE TITLE
Audio Jack - Fix after sleep 

### ISSUE THREAD

**Issue by gplast** [yusifsalam/t490-macos#26]
Hello and thank you for the amazing work and the effort,

I decided to change my drive finally and use t490 with Mac OS ( :) ), and is working perfectly with Big Sur with your repository!! (and the WIFI of course)

I have also a Mi Notebook Pro which works perfectly and i'm trying to find a way to make Audio Jack work after sleep. Based on the Mi Notebook Pro, we are using CodecCommander.kext to make this work. I found a script online, that as soon as you run it after sleep it makes audio jack work again.

I'm still trying to make the script run automatically after sleep and i will get back to you with that.
Attached is the kext that i put on the EFI partition and the script that i'm using after sleep.

Hope that helps and thank you again :) 

[enable_jack.zip](https://github.com/yusifsalam/t490-macos/files/5533637/enable_jack.zip)

**Comment by yusifsalam** [comment]
I've found that simply putting the laptop to sleep and waking it again somehow fixes the issue most of the time. This hack even works for when wifi can't connect or audio randomly disappears.
