### ISSUE TITLE
Issue Occured "an internet connection is required to install macOS"

### ISSUE THREAD

**Issue by xn5lnd** [yusifsalam/t490-macos#29]
Help please.
I use all the files provided above.
While intall macOS big sur, a problem occured :
"an internet connection is required to install MacOS"
Than I change the Info.plist file under volum "/oc/kexts/itlwm.kext"
FROM " <key>OSBounderRequired</key><String>Network-Root</String>"" TO
 <key>OSBounderRequired</key><String>Root</String>

it doesn't work.
Help please.Thanks

**Comment by yusifsalam** [comment]
You should be able to use the wifi picker in the installer.

For clarification, airportitlwm kext is the one responsible for wifi, not itlwm. Have you made any other changes to the EFI? Have you tried with an ethernet cable instead of wifi?

**Comment by xn5lnd** [comment]
I did some changes to the file provided above.
i am now trying another time using file without any changes  , it worked.Wifi connection works well~~
Thanks a lot~~
