### ISSUE TITLE
Lenovo T490 (i7 version)

### ISSUE THREAD

**Issue by gplast** [yusifsalam/t490-macos#3]
Hello and thank you for sharing with us you repository.,

Since i was using Clover for my previous hackintosh and i'm not familiar with OpenCore i would like to ask you if you can help me understand what is wrong with my configuration.

I have also a Lenovo t490 but the i7 vPro version (i7-8665U - Samsung MZVKB1T0HBLR-000L7).
I also have a samsung NVME connected on it. I managed to boot into the installation using you're configuration but at random times it the laptop freezes. I tried to format the disk in both Mac OS extended and apfs but some times i can format the disk and other times it freezes and i have to force shut it down.

In some cases the installation finished and reboots and then it freezes on the next page showing the Apple logo and "Estimating time remaining or 13 minutes remaining". I believe that there is something wrong with my configuration with respect to the SSD, do you have something in mind that might cause this issue?

I tried many things and other repositories but i'm getting the same behaviour with random freezes and i cannot finish the installation. As i said i have some experience with Clover and Hackintosh with a Dell latitude and a Mi Notebook Pro, but with this one i cannot find a solution.

I will really appreciate it if you can help me or at least give me a hint on how to solve this issue :) 

Thank you in advance!

**Comment by yusifsalam** [comment]
Have you made all the bios changes that I have listed in the readme? Specifically make sure your laptop is set to UEFI mode only and CSM support is disabled. 
Other than that I can't really think of any quick fix unfortunately, as samsung ssds should work out of the box on mac os. It's also possible that your mac os installer usb is corrupted for some reason, so try to make another usb installer and see if it helps.

**Comment by gplast** [comment]
Thank you for the reply,

Yes i followed all of your suggestions and i disable everything on the BIOS. I also tried to create the USB multiple times with multiple ways but i'm getting the same error every time. I guess i can try downloading again the installation to see :)

I believe that has something to do with the SSD since, every time that i'm trying to format it, the disk utility freezes, and i'm not able to see any log error. 

Btw if you didn't see it, you can download both files from below. Replace itlwm on the clover/kext/other/ with the one below and run Heliport.app when you boot in your system. You will be able to search and connect to the WIFI. I'm using it on my Mi Notebook Pro and i working great.

[itlwm+Heliport 2020.6.21.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4808892/itlwm%2BHeliport.2020.6.21.zip)

_Originally posted by @stevezhengshiqi in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/330#issuecomment-647075930_

Thanks again and if i find the issue i will let you know!

**Comment by yusifsalam** [comment]
Excellent suggestion about HeliPort! If you have any other similar suggestions to improve this project, please do share.

For error logging, you can enable verbose mode in OpenCore. In config.plist navigate to NVRAM-Add-7C436110-AB2A-4BBB-A880-FE41995C9F82, find boot-args and add "-v". If you want even more error logging, you can also change to the debug version of OpenCore and enable logging to file, consult the [OC laptop guide](https://dortania.github.io/vanilla-laptop-guide/) for more information.

**Comment by gplast** [comment]
Thank you very much for the help, i will test it and let you know.

I hope that i will also make it work and contribute as much as i can :) 

One last thing, can you share your EFI partition that you used when you proceed with the installation of Mac? Did you used a simpler one, without kexts or patches? 

Thank you again!

**Comment by yusifsalam** [comment]
I don't have the exact EFI I used to install the OS anymore but [this](https://github.com/yusifsalam/t490-macos/tree/07a2cf2c10d9ebb0d6c0baa5541f6f3dfd5d09c0) should be close enough. There is quite a lot of extra stuff there that you don't need for the installation, but that's because my starting point was my desktop EFI.

You can also just use the latest commit and disable all the extra fluff in the config file. So for the ACPI, go to the config file ACPI-Add and set Enable to false in all the entries and repeat for ACPI-Patch entries. For kexts, VirtualSMC and Lilu are the only required kexts but note that your keyboard and touchpad won't work without the Voodoo kext. You can disable kexts from the config file's Kernel-Add section.

**Comment by gplast** [comment]
Thank you very much, i really appreciate it. As i said this is the first time that i'm using opencore so i need to catch up with a lot of stuff.  I believe that i will find a way to make it work, and i will let you know. 

I removed all the ACPI patches and i manage to format my drive without a system freeze which is promising, but it freezes during the installation. I will let you know either way :)

Thanks!

**Comment by gplast** [comment]
Hello @yusifsalam,

After spending a lot of time and several attempts it seems that we are not able to run Mac OS on this particular model if it has a PM981 drive (which i have in my case).

Unfortunatelly i have to use this particular drive since this is a laptop that i was given by my work. I did replace the drive just to test if your OpenCore configuration works on this model also and is working create. 

I also tried this sugestion: https://github.com/tylernguyen/x1c6-hackintosh/issues/43#issue-594760774
But i was not able to boot into my system since i always get Kernel Panics from my NVME drive. 

I hope that at some point NVMEFix(https://github.com/acidanthera/NVMeFix) will be able to solve this issue and at some point i i will try the Big Sur update, just to see whether we have better outcome.

Thank you again for sharing this repository, i wish that at some point i will be able to run MacOS on my device and help on this effort.

Have a nice day,
--George

**Comment by yusifsalam** [comment]
Thank you George for your contributions!
It is an unfortunate situation, perhaps you could use a compatible drive in an empy PCI slot if your work permits that. 

For now I am closing this issue and will update the README regarding drive compatibility.

**Comment by rjrusek** [comment]
Dear yusifsalam,

**Comment by yusifsalam** [comment]
@rjrusek you should modify the config file according to [this page](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html#starting-point). My guess is that if you change RebuildAppleMemoryMap (in config-Booter) to true, it should help.

**Comment by rjrusek** [comment]
Yusif,





 Unfortunately this setting is already set to true.   Seems that when it
gets to that point the entire system just locks up.
