### ISSUE TITLE
Lagging when using macOS

### ISSUE THREAD

**Issue by ruskiballer** [yusifsalam/t490-macos#31]
**Describe the bug**
Me again. I told in my last issue that I tested the installation with another ssd and everything worked. Now I used the OS and especially when connecting and external monitor with HDMI the animations and the cursor are lagging. Did somebody has this before? Is this a issue with the graphic unit?

**Hardware**
Intel i5-8365U
16GB RAM
Intel UHD 620 Graphics

**Software and firmware**
macOS version: Big Sur
BIOS is the newest
OpenCore is the version provided in this repo

**To Reproduce**
I think it is a problem with the graphics unit. Do I need to change something post-install?

**Expected behavior**
Shouldn't lag because the hardware is comparable with a Macbook Pro

**Comment by yusifsalam** [comment]
It seems like you don't have hardware acceleration working on your GPU.

If you open About this mac - System report - Graphics - Metal family, what does it says there? It should say something like "Supported, Metal GPUFamily macOS 2"

**Comment by ruskiballer** [comment]
> It seems like you don't have hardware acceleration working on your GPU.
> 
> If you open About this mac - System report - Graphics - Metal family, what does it says there? It should say something like "Supported, Metal GPUFamily macOS 2"

I checked it and it says "Supported, Metal GPUFamily macOS 2"

**Comment by yusifsalam** [comment]
Huh, everything is very smooth on my machine and with GPU acceleration working it should be on yours too. Do you mind filming a video for me to show the sluggishness that you're describing? Can you also run cinebench and report your score.

**Comment by ruskiballer** [comment]
![Cinebench](https://user-images.githubusercontent.com/74879217/100195905-52bfca00-2ef8-11eb-8010-08ab3dcb47a9.png)

Isn't Cinebench only for CPU?

https://streamable.com/6r3rdo
Video #1 

https://streamable.com/0z1yl2
Video #2

The videos itself are a bit laggy. Especially the lags on the second video. But as soon as I move the mouse on YouTube Videos its stopping the video (audio works).

Idk what this is because I used your files. Idk if this is a problem with the external display, because it is to much work for the gpu.

**Comment by yusifsalam** [comment]
That is definitely not normal stuttering (there shouldn't be any, really). Your cinebench score is really low, because my older generation lower-clocked CPU has about 40% better scores.
![image](https://user-images.githubusercontent.com/42574232/100203530-66c0f700-2f0b-11eb-9422-9aa00210d5ca.png)

I'm not really sure why it is like that for you but I would start with disabling CPUFriend (which handles CPU power management and frequency vectors) and if that doesn't help, disable all non-essential kexts and patches and see if that does anything. 

To rule out faulty hardware, do you have Windows or Linux installed on the same machine? How is the performance for those, do you get similar cinebench scores? Also, which SSD are you using now, can you try with another one?

**Comment by bnexd** [comment]
Okay thats weird.
I tested it on Win10 and the MC Cinebench is also worse.
![Cinebench Win](https://user-images.githubusercontent.com/29842996/100214523-4b0c1f80-2f10-11eb-9fc3-7ad44982ba4e.png)

I'll try to play around with the kexts, but its weird that it is smooth on your machine and buggy on mine😅

**Comment by ruskiballer** [comment]
Okay I finally got some new results.
I deactivated both CPUFriend kexts and changed the key AAPL, ig-platform-id to 0900A53E and device-id to A53E0000. 
No everything seems to be smooth. The lags on YouTube stopped and moving windows is also smooth. Idk why I need to change these values and your values don't work for me but now we're here and its working.
Idk if you want to add a hint at the ReadMe for people with the same setup like me. 
I've got the values from https://elitemacx86.com/threads/intel-uhd-graphics-620-whiskey-lake-on-laptop-clover-opencore.455/

Thank you for your help :)

**Comment by yusifsalam** [comment]
Great to hear you've figured out a solution. I should definitely add something in the README about the GPU config. If I recall, I've actually tried those same values that you changed to but those broke HDMI output or something.

**Comment by ruskiballer** [comment]
> Great to hear you've figured out a solution. I should definitely add something in the README about the GPU config. If I recall, I've actually tried those same values that you changed to but those broke HDMI output or something.

Okay thats weird. HDMI output works fine for me. Maybe you create a section with solutions that might work for problems like this :)

Nevertheless great work from you and a nice support 🥇
