### ISSUE TITLE
YogaSMC failed

### ISSUE THREAD

**Issue by gfalo10** [yusifsalam/t490-macos#34]
Hello!!

I have updated the EFI folder with the latest YogaSMC kext, installed YogaSMCNC and when I run it I get the following message "Failed to connect to YogaSMC"
Do I have to do something else for it to work properly?

**Comment by yusifsalam** [comment]
YogaSMC is still a work in progress for now and I will update it when I have the time. 
The error message just means that the app does't have the write rights. Do the media keys like bluetooth wifi toggles work for you? You should also be able to read the CPU fan RPM with iStatmenus for example.

**Comment by gfalo10** [comment]
Ok, I wait then.
No works bluetooth wifi toggles...
Thanks

**Comment by yusifsalam** [comment]
@gfalo10 it should be working now. you also need to get the app from here https://github.com/zhen-zen/YogaSMC/suites/1723497340/artifacts/32607265

**Comment by gfalo10** [comment]
i´ve the same failure...just copy EFI and copy in applications YogaSMCNC...and when open it: "Failed to connect to YogaSMC"
Preferences panel don't work properly either.
I think I´m not installing it properly maybe?

**Comment by yusifsalam** [comment]
@gfalo10 you sure you have this in your config? https://github.com/yusifsalam/t490-macos/blame/master/OC/config.plist#L703-L721

**Comment by gfalo10** [comment]
Yes, I have that in my config file. But in my bootlog appears this:
"01:396 01:115 OC: Prelinked injection YogaSMC.kext () - Invalid Parameter"

Attach bootlog.				
[opencore-2020-12-26-153206.txt](https://github.com/yusifsalam/t490-macos/files/5743281/opencore-2020-12-26-153206.txt)

**Comment by yusifsalam** [comment]
Do you have all the latests kexts? In particular make sure VirtualSMC is the latest version.

**Comment by gfalo10** [comment]
Yes, I´ve copied your EFI folder completely, the version of VirtualSMC is 1.1.9

**Comment by yusifsalam** [comment]
I'm not really sure then, probably easiest to open an issue in YogaSMC repo or ask the developer directly in the gitter room.

**Comment by gfalo10** [comment]
OK, thanks a lot. But in your case is it working fine with the same EFI folder?
Maybe I´ve some application installed that block YogaSMC

**Comment by yusifsalam** [comment]
Yes, I'm using my EFI folder obviously :D
Almost everything is working for me: I can read fan speed and even change it manually, adjust power settings, only thing missing for me is the cycle count of the battery.

**Comment by yusifsalam** [comment]
Closing for now since I can't replicate and there is no new activity.
