### ISSUE TITLE
Battery status?

### ISSUE THREAD

**Issue by wtfmate79** [yusifsalam/t490-macos#37]
**Describe the bug**
I have added SSDT-BAT.aml to my ACPI folder and defined it in config.plist in the SSDT section at the top, but still dont see the battery status
**Hardware**
My hardware is identical to yours

**Software and firmware**
Big Sur 11.1, whatever is in your config, OpenCore latest debug. 

**Expected behavior**
No battery status

**Comment by yusifsalam** [comment]
If you're not using the latest BIOS and EC, then you should update and report back.

If your'e already on the latest BIOS and EC, then I'm not really sure. There's been a few reports of battery indicator not showing and I haven't been able to figure out why.

**Comment by wtfmate79** [comment]
![A3D9D723-051B-4F89-8712-94CF5C458EDA](https://user-images.githubusercontent.com/77924381/105923435-5d870000-600a-11eb-8052-759dba12d97a.jpeg)

Here is my system bios ver. Is there anything else I need to add apart from the bat alm to config?

**Comment by yusifsalam** [comment]
You don't have the latest version.
You can get it from here https://support.lenovo.com/fi/en/downloads/ds539061-bios-update-utility-bootable-cd-for-windows-10-64-bit-and-linux-thinkpad-t490-t590-p53s-p43s

**Comment by wtfmate79** [comment]
> You don't have the latest version.
> You can get it from here https://support.lenovo.com/fi/en/downloads/ds539061-bios-update-utility-bootable-cd-for-windows-10-64-bit-and-linux-thinkpad-t490-t590-p53s-p43s

Thank you, i will try this and report back. Would showing you my EFI tree also help you in diagnosing my issue?

**Comment by yusifsalam** [comment]
Your EFI tree should look identical to the one in this repo, the only difference would be the serials in the config.plist file. 

Assuming you're using my EFI (with your own serial numbers) as provided, your battery indicator _should_ work but if it doesn't, that probably means your DSDT is different from mine, so you would need to make your own battery patch.

**Comment by wtfmate79** [comment]
> Your EFI tree should look identical to the one in this repo, the only difference would be the serials in the config.plist file.
> 
> Assuming you're using my EFI (with your own serial numbers) as provided, your battery indicator _should_ work but if it doesn't, that probably means your DSDT is different from mine, so you would need to make your own battery patch.

It was a combination of yours and another GitHub member but since she removed hers and I have no way of contacting her.

Here is mine: https://pastebin.com/We2R8tiU

I originally could not boot up recovery with yours, If I were to copy yours onto a USB and try to boot, would that work?

**Comment by wtfmate79** [comment]
> Your EFI tree should look identical to the one in this repo, the only difference would be the serials in the config.plist file.
> 
> Assuming you're using my EFI (with your own serial numbers) as provided, your battery indicator _should_ work but if it doesn't, that probably means your DSDT is different from mine, so you would need to make your own battery patch.

When I try to boot your OC files, boot hangs on apple logo and no idea why. I dont know how to enable verbose boot, but I can see OC creates a log. Here it is:

https://pastebin.com/mEEG59iw

Any help you could provide would be greatly appreciated.

**Comment by yusifsalam** [comment]
Your pastebin is expired. To enable verbose mode, add "-v" here https://github.com/yusifsalam/t490-macos/blob/6878f3056b43bd3e4df8bd92bc7a32f75f6e07b0/OC/config.plist#L1428

**Comment by wtfmate79** [comment]
> Your pastebin is expired. To enable verbose mode, add "-v" here
> 
> https://github.com/yusifsalam/t490-macos/blob/6878f3056b43bd3e4df8bd92bc7a32f75f6e07b0/OC/config.plist#L1428

https://pastebin.com/dNkiRFqp

try this link, in the meantime i will try verbose

**Comment by wtfmate79** [comment]
> Your pastebin is expired. To enable verbose mode, add "-v" here
> 
> https://github.com/yusifsalam/t490-macos/blob/6878f3056b43bd3e4df8bd92bc7a32f75f6e07b0/OC/config.plist#L1428

Here is where it hangs on boot:

https://imgur.com/PGh5sey

**Comment by yusifsalam** [comment]
Same error

**Comment by wtfmate79** [comment]
> Same error

I dont know why its being taken down. 

[opencore-2021-01-28-164539.txt](https://github.com/yusifsalam/t490-macos/files/5888805/opencore-2021-01-28-164539.txt)

**Comment by yusifsalam** [comment]
Are you using my exact EFI as-is (with your own serials) or do you have other stuff mixed in?

**Comment by wtfmate79** [comment]
> Are you using my exact EFI as-is (with your own serials) or do you have other stuff mixed in?

I have not edited anything except for config file to add battery aml

here is my file:


[config.plist.zip](https://github.com/yusifsalam/t490-macos/files/5889408/config.plist.zip)

**Comment by yusifsalam** [comment]
why are you using a different config? it's already provided here in this repo, all you have to do is replace the serials that are marked "XXX" under PlatformInfo-Generic.

**Comment by wtfmate79** [comment]
> why are you using a different config? it's already provided here in this repo, all you have to do is replace the serials that are marked "XXX" under PlatformInfo-Generic.

I was able to get your config to work, so i found the one i posted here.

Anyways, I updated a valid serial, UUID, ROM etc in your config, it boots further now but now kernel panics. See image.

![IMG_3633](https://user-images.githubusercontent.com/77924381/106216092-5b56aa00-61a0-11eb-9c96-657aed2eb12a.jpeg)

**Comment by wtfmate79** [comment]
Hello,

Just wondering if you have any idea or is my issue a lost cause?

**Comment by yusifsalam** [comment]
You could try something similar to this: https://github.com/yusifsalam/t490-macos/discussions/36#discussioncomment-333642

**Comment by wtfmate79** [comment]
> You could try something similar to this: [#36 (reply in thread)](https://github.com/yusifsalam/t490-macos/discussions/36#discussioncomment-333642)

I replaced the AML but sadly not working. In his case he could at least see 0%, i dont get anything at all.

**Comment by yusifsalam** [comment]
Closing since no new activity.
