### ISSUE TITLE
t590更换屏幕后无法进入系统

### ISSUE THREAD

**Issue by 1074566721** [yusifsalam/t490-macos#42]
T590 更换高色域屏幕后无法进入系统，如下图所示
![U1`07LX4M_MUQNSC2B}}$KK](https://user-images.githubusercontent.com/67006196/129654754-85e277af-7326-44a4-9c10-87bdf010d44e.jpg)
还有一个问题，数字小键盘NumLock按键灯不亮

**Comment by yusifsalam** [comment]
Please use the provided issue template and write in English.
