### ISSUE TITLE
Testing of untested functionality

### ISSUE THREAD

**Issue by yusifsalam** [yusifsalam/t490-macos#9]
Help is needed to test certain features that I'm not able to test myself or need more evidence! 
Currently the features that need more testing are:
- Sidecar, both wired and wireless: not working
- Touchscreen
- Thunderbolt (TB)
- CPU fan info
- Other features that I'm not remembering, which?

Updated to working:
- AirPlay (3 reports)
- CPU temps (3 reports)

Updated to NOT working:
- Sidecar, wired or wireless (1 report)
- Touchscreen (1 report)
- TB bridge (1 report)
- CPU fan stats (2 reports)
- CPU temp (1 report)

**Comment by Jpeace7** [comment]
side car doesn't work both wired and wireless .message Unable to Connect to “iPad” the device timed out .

airplay works 

thunderbolt bridge doesn't work 

cpu sensors temps not available , fan temp not available , only one visible now is hard drive temp 

touch screen doesn't work . 
![Screen Shot 2020-09-18 at 12 52 01 AM](https://user-images.githubusercontent.com/67621911/93571371-32e4b680-f949-11ea-82e2-1ac44487b1a5.png)

**Comment by yusifsalam** [comment]
@Jpeace7 Thanks!
Interesting, I think sidecar should work in wired mode without much change, maybe create a new USB map? 

CPU temps are working fine for me in Intel Power Gadget 3.7.0, are you testing with the Intel Power Gadget and what's your cpu? CPU fan stats are indeed not visible for me either. 

For touchscreen you probably need to enable i2c in VoodooRMI. My device doesn't have a touch-enabled screen so I can't really comment beyond that, please consult the [VoodooRMI repo](https://github.com/VoodooSMBus/VoodooRMI).

**Comment by Jpeace7** [comment]
will sidecar doesn't work in two different modes . it connects wirelessly only and connecting the cable only charges the iPad according to apple . some people say its better to connect it for better latency  but I can't anything that supports it . I tested it on an apple device the thing just works regardless if its plugged or not . I highly doubt anybody with a hackintosh will be looking to get this feature . in my opinion airdrop is much more important and more usable . 

as far as cpu temps it was working before . everything was visible on Mac fan control except fans but now with this brand new build I installed today its not working . so I need to check that . the cpu is intel core I5 8th Gen. 

the problem I have is I can't get  voodooRMI and Voodoops2 to work together and for now I think I would rather not have voodooRMI because it continues to have issues for me .

**Comment by yusifsalam** [comment]
As far as I'm aware you don't have to connect wirelessly to use Sidecar, it should work over USB without WiFI or Bluetooth. I don't own an iPad myself though, so I could be wrong. I will test with my friend's iPad when I get the chance. I think you mean AirPlay and not AirDrop, because AirDrop does not mirror or extend your display so it's not really comparable to Sidecar.

I'm not sure I understand why you're having issues with VoodooPS2, did you manage to get the trackpad detected by the OS? Assuming we have the same trackpad model, I recommend you use my latest config file and manually replace the VoodooPS2 kext with the one from [here](https://github.com/acidanthera/VoodooPS2/releases/tag/2.1.6). 

Did you get the battery indicator working btw?

**Comment by Jpeace7** [comment]
Yes sorry my bad i meant AirPlay . I don’t think you can because according to Apple you need Wi-Fi Bluetooth enabled  and you also need to factor iCloud authentication enabled to get side car working  for some reason . 

Yes I finally was able to get the trackpad and battery working with this new install i did today . 

What I mean is I can’t get voodoormi and voodoops2 to Work together  . I need voodoormi to try to get the touchscreen working but the trackpad doesn’t work that good . there is a lot of lag especially if it was in sleep mode and for some reason it doesn’t act nice with My Bluetooth devices . I think I will need to manually turn off some features to get it to work right

**Comment by Jpeace7** [comment]
for side car I tested it wirelessly it didn't work .
I tried connected a thunderbolt cable . it charges the iPad but that's it same error when connecting 
I tried a usb-c cable same thing . 
I did try the same connections on a iPad and MacBook and all of them worked .

let me know if you need to test it any other way .

**Comment by yusifsalam** [comment]
For touchscreen you could try to ask for help in [VoodooRMI gitter room](https://gitter.im/VoodooSMBus/dev), because the driver works perfectly on my machine albeit without touchscreen.

**Comment by denzilferreira** [comment]
![Screenshot 2020-09-18 at 14 01 20](https://user-images.githubusercontent.com/8342829/93590587-7249ec00-f9b7-11ea-864b-bf3aacd64694.png)
CPU cores temps + SSD temperature working fine here. Using iStat Menus.

**Comment by Jinglong-Hongjun** [comment]
CPU Temp, HDMI with audio, USB-C (to VGA) are working but I have thermal throttling issue (at 65 degC) and no battery icon.
I'm using T490 (20N2) i7 8565U with MX250 BIOS: 1.49 EC: 1.12 (maybe or 1.14) 
![Screen Shot 2563-09-18 at 20 58 41](https://user-images.githubusercontent.com/71412080/93607021-fe2d3980-f9f2-11ea-97ce-ee8f3dab5168.png)
Thank you

**Comment by yusifsalam** [comment]
@Jinglong-Hongjun thanks, can you open a new issue about throttling? I just ran cinebench r20 on macOS and got 1170, also on windows I got 1212 on battery and 1278 plugged in (both set to max performance, macOS set to power saving). My CPU throttled down quite a bit but was still running at 2.5ghz for the entire duration, temp was a toasty 97c. 
Can you try to disable CPUFriend and try again?

**Comment by denzilferreira** [comment]
Some findings regarding VoodooRMI driver. If you set your clicking as shown in the screenshot, you get the click on the trackpad (actually comes from the tap, but hey, it works!). Tested all the gestures and they are working! Only limitation is if you need to click-hold-drag, then you need to use the physical button on the trackpad.

![Screenshot 2020-09-19 at 17 32 56](https://user-images.githubusercontent.com/8342829/93669663-68e77f00-fa9e-11ea-9e82-2374e3a6cc02.png)

**Comment by denzilferreira** [comment]
Also, using iStat Menus, I actually get a time left on the battery. I don't see it on the native battery indicator, but it works with this software!

![Screenshot 2020-09-19 at 17 36 43](https://user-images.githubusercontent.com/8342829/93669724-d398ba80-fa9e-11ea-9076-a7e34c180c19.png)

**Comment by denzilferreira** [comment]
Just a note: if you press the Print Screen button on the keyboard (next to AltGr), you disable the trackpad. Just in case someone loses his mind because the trackpad all of the sudden stopped working and they can't figure it out.

**Comment by denzilferreira** [comment]
I've fixed the automatic brightness for the screen, CPU throttle and having the audio support over USB-C and HDMI.

- For automatic brightness control, you need to add SSDT-ALS0 to your config.
Get it from here: [SSDT-ALS0.aml.zip](https://github.com/yusifsalam/t490-macos/files/5250218/SSDT-ALS0.aml.zip)

- For CPU throttle fix, you need to have the SSDT-PLUG-DRTNIA in your config.
Get it from here: https://dortania.github.io/Getting-Started-With-ACPI/Universal/plug-methods/prebuilt.html

- For fixing the audio and display quirks, only set this on the DeviceProperties:
![Screenshot 2020-09-19 at 19 58 10](https://user-images.githubusercontent.com/8342829/93672298-8cb4c000-fab2-11ea-851a-c1958e668252.png)

- Set the AppleALC correctly with this boot args: alcid=11

**Comment by yusifsalam** [comment]
@denzilferreira very nice findings, really great to have you here!
I'm not really a fan of tap to click to be honest, I just use the trackpoint buttons. Also, I tried the RMI driver under linux and the trackpad hardware button did not work (I believe it's using the F3A function, which the linux kernel does not have the code for), so it's going to require quite a bit of work to get this working with VoodooRMI. I wonder what implementation windows is using, is it just PS2?

For the battery, at least a while ago the native widget was showing the estimated time remaining, not sure if bios update or macOS update killed it. Either way it's nowhere near accurate to be particularly useful, so I don't really mind not having it. 

For CPU throttling, I already am injecting SSDT_PLUG, the dortania version is the same thing but with more devices that this laptop does not have. You can disassemble the SSDT-PLUG from this repo using MaciASL and compare it to the dortania version and the full DDST file of the laptop. 

Do you mean the whole GPU device section is not needed or does that only fix audio? If you could open a PR with the changes you made (also including other tweaks, maybe not the SSDT-PLUG unless I'm wrong about that), that would make it a lot easier for me to test.

Thanks again, at some point I'll probably create a separate document describing all these findings and little quirks, just to have it all in one place.

**Comment by denzilferreira** [comment]
> @denzilferreira very nice findings, really great to have you here!
Thank you for putting all of this together :) hyvää tyotävää!

> I'm not really a fan of tap to click to be honest, I just use the trackpoint buttons. Also, I tried the RMI driver under linux and the trackpad hardware button did not work (I believe it's using the F3A function, which the linux kernel does not have the code for), so it's going to require quite a bit of work to get this working with VoodooRMI. I wonder what implementation windows is using, is it just PS2?

Yeah, I also reverted back to the PS2. It works reliably enough.

> For the battery, at least a while ago the native widget was showing the estimated time remaining, not sure if bios update or macOS update killed it. Either way it's nowhere near accurate to be particularly useful, so I don't really mind not having it.

Using iStat Menus, I do get a realistic time remaining. Works great and I've been actually enjoying 5-6h of battery life with a 1.5 Wh power decrease on average with the display half-bright.

> For CPU throttling, I already am injecting SSDT_PLUG, the dortania version is the same thing but with more devices that this laptop does not have. You can disassemble the SSDT-PLUG from this repo using MaciASL and compare it to the dortania version and the full DDST file of the laptop.

Yes, you are right, I removed it and all is OK.

> Do you mean the whole GPU device section is not needed or does that only fix audio? If you could open a PR with the changes you made (also including other tweaks, maybe not the SSDT-PLUG unless I'm wrong about that), that would make it a lot easier for me to test.

I've been spending time testing all the possible combinations of this. On my laptop, everything is now working, including audio over DP and HDMI!

![Screenshot 2020-09-22 at 10 09 52](https://user-images.githubusercontent.com/8342829/93853359-6a8e8e00-fcbc-11ea-851c-c0bdc32b98e6.png)

I was reading about what works and doesn't work on UHD 620. In the DeviceProperties, all you need is this:
![Screenshot 2020-09-22 at 10 17 19](https://user-images.githubusercontent.com/8342829/93853607-cfe27f00-fcbc-11ea-9d47-9adf54bc3970.png)

And under NVRAM, boot-args needs this to get the audio over DP and HDMI to be detected: keepsyms=1 debug=0x100 alcid=11 -wegnoegpu

The alcid=11 identifies correctly the audio card and the -wegnoegpu tells the audio controller that you have HDMI/DP output capabilities! Tested and working!

**Comment by yusifsalam** [comment]
@denzilferreira can you check if audio over usb-c works now with the latest commit?

**Comment by denzilferreira** [comment]
Yep 👍 I’ll check both HDMI 1440p and USB-C later today!

D

#> sudo mail from:Denzil
#> Sent successful (elapsed .001 seconds)

**Comment by denzilferreira** [comment]
OK, using the latest configuration, I get HDMI and audio working over HDMI, but no audio over USB-C. I went to the BIOS to change between HDMI and USB-C shared display priorities, no change in the displaying audio out in the USB-C connection for the display. In DeviceProperties, I tried removing the PciRoot that was regarding the audio, no change - we actually don't need it since we have the alcid=11 on the boot-args. Hot Plugging HDMI is working and audio out is detected. Only the USB-C audio is not working at the moment. Both working at 60Hz. Until we figure out why doesn't the USB-C audio out work, this works better than before 👍 

![Screenshot 2020-09-24 at 9 52 16](https://user-images.githubusercontent.com/8342829/94111745-241c6900-fe4d-11ea-9a63-0361b060bb86.png)

**Comment by yusifsalam** [comment]
@denzilferreira wifi has been rock solid for me over 5ghz (which is what the devs at OpenWireless recommend if you're using both wifi and bluetooth), bluetooth can sometimes refuse to cooperate yeah but a restart always fixes that.

**Comment by denzilferreira** [comment]
> @denzilferreira wifi has been rock solid for me over 5ghz (which is what the devs at OpenWireless recommend if you're using both wifi and bluetooth), bluetooth can sometimes refuse to cooperate yeah but a restart always fixes that.

Yeah, using 5GHz today and it has been working non-stop! Thanks!

**Comment by Jpeace7** [comment]
how did you get auto brightness to work ? I tried the fix from up top . still can't see auto brightness

**Comment by Jpeace7** [comment]
![Screen Shot 2020-09-25 at 12 10 23 AM](https://user-images.githubusercontent.com/67621911/94237354-962f9500-fec3-11ea-9da1-47a3902b8d73.png)
this patch fixed my  problem of not being able to use all usb and usb-c ports all at ounce

**Comment by denzilferreira** [comment]
> ![Screen Shot 2020-09-25 at 12 10 23 AM](https://user-images.githubusercontent.com/67621911/94237354-962f9500-fec3-11ea-9da1-47a3902b8d73.png)
> this patch fixed my problem of not being able to use all usb and usb-c ports all at ounce

Can you point us to where you got the patch from? So we can add to the config.plist 👍  Or you do it and do a PR :)

**Comment by yusifsalam** [comment]
I don't think it's necessary if you do your own USB map. You can do so by following this guide:
https://dortania.github.io/OpenCore-Post-Install/usb/

**Comment by benbender** [comment]
@yusifsalam is correct. The patch is only needed while generating the a usb-portmap and injecting all possible ports via USBInjectAll.kext. And even than it's replaced by the builtin "XHCIPortLimit"-option of OpenCore (also seen in the bottom right of the screenshot). So the manual patch is never needed :)

**Comment by yusifsalam** [comment]
Sidecar wireless not working, did not try wired.
